### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by REJack** [twolfson/livereload-extensions#4]
Hey together, 

I hate the icons a bit since I got my new screen 😬 the colors are not perfect and they look too blurry.

I've reworked the Icons according to Firefox's new [Photon Design System](https://design.firefox.com/photon/visuals/iconography.html)

I've reworked all icons in Adobe Illustrator, i found the right color for Firefox "light" theme, swapped the colors from `connecting` and `connected` and used the icon colors from Firefox itself.

Here are some previews:
![preview_ready](https://user-images.githubusercontent.com/1554582/33792002-3cdbf72a-dc96-11e7-9921-12232c750a59.jpg) ![preview_connecting](https://user-images.githubusercontent.com/1554582/33792003-3e1413fc-dc96-11e7-8be3-e7f130fab2a7.jpg) ![preview_connected](https://user-images.githubusercontent.com/1554582/33792004-3f124922-dc96-11e7-873d-bf907358d8ba.jpg)

All new icons in my previews are SVG's not PNG's, here is a preview for the diffence between SVG & PNG icons (both are my new icon).
![preview_svg_vs_png](https://user-images.githubusercontent.com/1554582/33792026-a4ff18b4-dc96-11e7-97a2-3a9bbb7bdf7a.jpg)

Last but not least, I've created also icons for Firefox's dark theme. (left light theme icon, right dark theme icon)
![preview_dark_theme](https://user-images.githubusercontent.com/1554582/33792071-9bd9edda-dc97-11e7-8b56-69e6c38a6dcc.jpg)
But for the dark theme we need a second addon, i found no way to catch which theme Firefox use. (`theme.getCurrent()` doesn't work with the builtin themes, only for custom themes :/)

P.S.: I've added no unavailable state preview, because I don't know how to trigger it 😁 but I reworked it too.

What you think about this?

**Comment by twolfson** [comment]
I think I'm open to it, although I don't think there's a whole lot of value add except for dark theme support. I'm going to defer to other icon enthusiats /cc @erikw

**Comment by twolfson** [comment]
It's been a week, I still feel apathetic about this. Feel free to open a PR or close the issue =)

**Comment by REJack** [comment]
Sorry for the delay, i hate the christmas season 😅

The big value is that every user gets a perfect looking icon in every dpi size, additional we can change quickly the colors of the icons without any Image Manipulation tool like Photoshop or GIMP and we can use the SVG's too to export the Chrome's & Safari's PNG files.

But only Firefox supports SVG's for Toolbar Icons at the moment.

I'll add in the next days a PR then you can look over my changes.

**Comment by gerdneuman** [comment]
Let me say: @twolfson  I cannot praise you enough, so happy that LiveReload works again in Firefox :)

And nice to see this issue being reported, as a dark theme user I came here to propose the same:

![image](https://user-images.githubusercontent.com/12525563/37592943-9deebc40-2b70-11e8-8e71-759a2e3fa2b8.png)

As a side note: The [XDebug helper](https://github.com/BrianGilbert/xdebug-helper-for-firefox) works as a page context icon, which seems more appropriate.

**Comment by twolfson** [comment]
@gerdneuman It looks like @REJack has a solution in #6 which we should land soon but I'd like to hear more about "page context icon". @gerdneuman Could you elaborate?

**Comment by gerdneuman** [comment]
I don't wanna bike-shed, surely #6 should get merged asap :)

Regarding, "page context icon": Per page actions like bookmarking, sending a tab to a mobile device, Screenshot tool or saving to Pocket are all contextual actions, that is, in the address bar (aka "awesome bar" as Firefox names it). 

OTOH, there a icons (so called "browser actions") in the browser toolbar which is where the LiveReload is also at the moment.

See: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Page_actions for page actions:

> Use a page action when the action is related to the current page, and a browser action when the action is related to the browser as a whole or to many pages. 

The page also has some examples in a table below this quote. Since LiveReload is for the current page, and not whole browser, according to Guidelines it should be Page not browser action.

Browser actions OTOH are described here:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Browser_action

**Comment by REJack** [comment]
Page actions sounds great, I'll try it out this week. 😄 I hate to much toolbar icons in my Firefox.

**Comment by twolfson** [comment]
Ah, very informative. Yea, I think the LiveReload architecture would be much saner with something like that. Prob out of scope for us as a fork though =/

Was there any benefit icon-wise though?

**Comment by gerdneuman** [comment]
> Prob out of scope for us as a fork though =/

Well, I remember creating issues about Firefox not working on the upstream github repo like 2 or 3 years ago... To which I never got any response (except +1 from other users). Also, upstream did not get any updates for almost 3 years now.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1172415#c6 This was not just about WebExtensions but also previously about e10s not being updated for by LiveReload authors. 

That's why I was so excited when I discovered this Extension here today: Finally, it's working again :)))  (because I thing the upstream repo has been abandanded to be honest)

**Comment by twolfson** [comment]
Ah, I see. I always downloaded from their site as well. Let's have the LTS discussion in another thread -- this repo is a fork which is bad for GitHub functionality (e.g. no search support) so we'd definitely to create a new one

**Comment by twolfson** [comment]
This issue has been resolved by @REJack in #6. The updates have been submitted as `20.3.0` to https://addons.mozilla.org/. It should get approved relatively soon (iirc it's within 10 minutes or so)

**Comment by gerdneuman** [comment]
@REJack @twolfson  Wow, the new icons look really, really cool in the dark theme. Great eye candy :) Chapeau!
